# Exported from https://tiplanet.org/pb/ on Thu Nov 16 13:35:06 2023 (CET)

# ----------------------------
# Program Options
# ----------------------------

NAME         ?= GRID3D
ICON         ?= icon.png
DESCRIPTION  ?= ""
COMPRESSED   ?= YES
ARCHIVED     ?= YES

# ----------------------------
# Compile Options
# ----------------------------

CFLAGS   ?= -Oz -W -Wall -Wextra -Wwrite-strings
CXXFLAGS ?= -Oz -W -Wall -Wextra -Wwrite-strings

# ----------------------------

include $(shell cedev-config --makefile)
